### ISSUE TITLE
Non-interactive mode

### ISSUE THREAD

**Issue by jtuchscherer** [cloudfoundry/firehose-plugin#1]
For better scriptability, the plugin should have an option to be non-interactive.

When a user passes in the `-n` flag, it should not prompt for filters. The user should still be able to pass in a filter with the `-f` or `--filter` flag with the string representation of the message type.

**Comment by wfernandes** [comment]
I get a `You are not allowed to view the requested page.` when i click on the pivotal tracker link. Is the tracker project not public?

**Comment by jtuchscherer** [comment]
@wfernandes I think the story got deleted, because it wasn't linked to the right tracker.

**Comment by jtuchscherer** [comment]
Fixed by 7dbe8d1ac698595433d44b4f26d56b3bbbd5bf9d

Thanks, @wfernandes
