### ISSUE TITLE
Refresh oauth-token automatically when it expires

### ISSUE THREAD

**Issue by roxtar** [cloudfoundry/firehose-plugin#12]
If the CF oauth-token expires, the nozzle plugin doesn't request for a new one. Instead it fails to authenticate. All the other cf commands go and get a new oauth-token and continue working.

**Comment by wfernandes** [comment]
After doing some investigating and verification, this is no longer an issue in CF CLI version 6.14. The `AccessToken()` will automatically refresh the token every time it is invoked. Upgrade to the latest CF CLI version.

For more info, 

[Github Issue](https://github.com/cloudfoundry/cli/issues/597)
[Tracker Story](https://www.pivotaltracker.com/n/projects/892938/stories/103908704)
[Git Commit](https://github.com/cloudfoundry/cli/commit/b16aad6d7c1bb4a3045a6e2d72a2df94efe712ae)
