### ISSUE TITLE
Allow a firehose subscription id to be passed in

### ISSUE THREAD

**Issue by jtuchscherer** [cloudfoundry/firehose-plugin#2]
If an user would want (for whatever reason) to have multiple CLI sessions going to connect to the firehose, we should allow for the firehose message being distributed evenly across the sessions. That is possible when the user can modify the subscription id.

The user should be able to do the with the `-s` or  `--subscription-id` flag.

**Comment by wfernandes** [comment]
Issue resolved with the following merge https://github.com/cloudfoundry/firehose-plugin/commit/f517b52000f417960cbc41bb5af900afa4cc7df3
