### ISSUE TITLE
Can't install firehose plugin using Readme

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry/firehose-plugin#28]
I tried installing the cf nozzle plugin today, and got the following error, which made it look like there's a typo somewhere:

```
cf install-plugin "Firehose Plugin" -r CF-Community

**Attention: Plugins are binaries written by potentially untrusted authors. Install and use plugins at your own risk.**

Do you want to install the plugin Firehose Plugin?> yes
Looking up 'Firehose Plugin' from repository 'CF-Community'
13926480 bytes downloaded...
Installing plugin ozzle-plugin-linux...
FAILED
fork/exec /tmp/ozzle-plugin-linux: permission denied
```

(`ozzle` vs `nozzle`)

**Comment by geofffranks** [comment]
FYI, saw this on cf CLI 6.22.2+a95e24c-2016-10-27 (darwin) and 6.23.1+a70deb3.2017-01-13 (linux).

**Comment by ahevenor** [comment]
Thanks @geofffranks - seems straightforward. I scheduled this for review.

**Comment by jtuchscherer** [comment]
Just as an FYI here:

I was able to see the `ozzle` typo on my Linux installation as well, but not on my Mac. However, on both systems (Mac and Linux on 6.23.1) I was able to install and run the plugin without any issues.

After looking into this for a little bit, I am stumped about the root cause. On the surface everything looks good. I would have expected to see the typo here: https://github.com/cloudfoundry-incubator/cli-plugin-repo/blob/master/repo-index.yml#L525-L526 , but that is all correct. I am sure the loggregator team can track this down.

**Comment by jasonkeene** [comment]
@jtuchscherer Thanks for looking into this a bit. I'm sure we can hunt it down.

**Comment by ahevenor** [comment]
This is no longer officially supported by the Loggregator team. This will need to be picked up by the community.

@wfernandes *ahem, cough cough*

**Comment by geofffranks** [comment]
Is there an officially supported cli firehose client that should be used instead?

**Comment by wfernandes** [comment]
@geofffranks As of now there is no official firehose cli client.

I was able to install the latest version of the plugin on ubuntu-linux x86_64 machine. My CLI version is `cf version 6.22.1+6b7af9c-2016-09-24`

I'll look into upgrading my CLI version to the most recent one and see if I can reproduce the error.

**Comment by wfernandes** [comment]
So I was able to successfully install the firehose plugin on my ubuntu-linux machine using the CLI `cf version 6.25.0+787326d.2017-02-28`

Can you try installing the plugin after upgrading to the latest CLI?

**Comment by geofffranks** [comment]
Fails for me on linux:

```$ cf -v
cf version 6.25.0+787326d.2017-02-28
$ cf install-plugin -r CF-Community "Firehose Plugin"

**Attention: Plugins are binaries written by potentially untrusted authors. Install and use plugins at your own risk.**

Do you want to install the plugin Firehose Plugin?> yes
Looking up 'Firehose Plugin' from repository 'CF-Community'
13926480 bytes downloaded...
Installing plugin ozzle-plugin-linux...
FAILED
fork/exec /tmp/ozzle-plugin-linux: permission denied
14:22:36 gfranks@east-us-proto-jumpbox-jumpbox {~/logsearch-deployments}(master)[2] $ sudo cf install-plugin -r CF-Community "Firehose Plugin"

**Attention: Plugins are binaries written by potentially untrusted authors. Install and use plugins at your own risk.**

Do you want to install the plugin Firehose Plugin?> yes
Looking up 'Firehose Plugin' from repository 'CF-Community'
13926480 bytes downloaded...
Installing plugin ozzle-plugin-linux...
FAILED
fork/exec /tmp/ozzle-plugin-linux: permission denied```

worked on darwin with `cf version 6.25.0+787326d95.2017-02-28` though

**Comment by geofffranks** [comment]
Interesting.. on my darwin machine, the plugin has installed as 
```
  "Plugins": {
    "FirehosePlugin": {
      "Location": "/Users/gfranks/.cf/plugins/ozzle-plugin-darwin",
      "Version": {
        "Major": 0,
        "Minor": 11,
        "Build": 0
      },
      "Commands": [
        {
          "Name": "nozzle",
          "Alias": "",
          "HelpText": "Displays messages from the firehose",
          "UsageDetails": {
            "Usage": "cf nozzle",
            "Options": {
              "debug": "-d, enable debugging",
              "filter": "-f, specify message filter such as LogMessage, ValueMetric, CounterEvent, HttpStartStop",
              "no-filter": "-n, no firehose filter. Display all messages",
              "subscription-id": "-s, specify subscription id for distributing firehose output between clients"
            }
          }
        },
        {
          "Name": "app-nozzle",
          "Alias": "",
          "HelpText": "Displays messages from the firehose for a given app",
          "UsageDetails": {
            "Usage": "cf app-nozzle APP_NAME",
            "Options": {
              "debug": "-d, enable debugging",
              "filter": "-f, specify message filter such as LogMessage, ValueMetric, CounterEvent, HttpStartStop",
              "no-filter": "-n, no filter. Display all messages"
            }
          }
        }
      ]
    },
```
```
$ ls -l
total 22932
-rwxr-xr-x 1 gfranks staff  9640924 Oct 16  2015 cf-plugin-kibana-me-logs
-rw------- 1 gfranks staff     1826 Mar 21 10:21 config.json
-rwx------ 1 gfranks staff 13833468 Mar 21 10:21 ozzle-plugin-darwin
```
Maybe the `ozzle` name is a red-herring based on bad output from the CF CLI? Looking through the code, seems like there should be more output when `CF_TRACE=true` is on, but I don't get any.

**Comment by wfernandes** [comment]
Is your machine 32bit or 64bit?

When we build the linux binary, it is compiled for `GOARCH=amd64`.

Also I just published an update to the plugin (0.12.0), try installing it again.

**Comment by wfernandes** [comment]
@geofffranks Just FYI, we've relocated the repo to https://github.com/cloudfoundry-community/firehose-plugin

We can continue this discussion here but please note future issues will be addressed over there. Thanks.

**Comment by geofffranks** [comment]
Nope, running 64-bit. I ran an strace on this and found the root of the problem being that my /tmp directory is mounted noexec, which prevents
the plugin from running on its own. Setting TMPDIR  to something I can write to let me install the plugin properly. It appears that the `ozzle` stuff
is in fact a red herring. Closing this.

Thanks for the help!
